// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: papers/v1/papers.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PaperServiceClient is the client API for PaperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaperServiceClient interface {
	GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error)
}

type paperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaperServiceClient(cc grpc.ClientConnInterface) PaperServiceClient {
	return &paperServiceClient{cc}
}

func (c *paperServiceClient) GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error) {
	out := new(GetCertificateResponse)
	err := c.cc.Invoke(ctx, "/papers.v1.PaperService/GetCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaperServiceServer is the server API for PaperService service.
// All implementations must embed UnimplementedPaperServiceServer
// for forward compatibility
type PaperServiceServer interface {
	GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error)
	mustEmbedUnimplementedPaperServiceServer()
}

// UnimplementedPaperServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaperServiceServer struct {
}

func (UnimplementedPaperServiceServer) GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedPaperServiceServer) mustEmbedUnimplementedPaperServiceServer() {}

// UnsafePaperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaperServiceServer will
// result in compilation errors.
type UnsafePaperServiceServer interface {
	mustEmbedUnimplementedPaperServiceServer()
}

func RegisterPaperServiceServer(s grpc.ServiceRegistrar, srv PaperServiceServer) {
	s.RegisterService(&PaperService_ServiceDesc, srv)
}

func _PaperService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaperServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/papers.v1.PaperService/GetCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaperServiceServer).GetCertificate(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaperService_ServiceDesc is the grpc.ServiceDesc for PaperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "papers.v1.PaperService",
	HandlerType: (*PaperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCertificate",
			Handler:    _PaperService_GetCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "papers/v1/papers.proto",
}
