version: "3.9"
services:
  server:
    image: github.com/larwef/papers-please/server:${VERSION}
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - papersPleaseNetwork
  client:
    image: github.com/larwef/papers-please/client:${VERSION}
    environment:
      - CLIENT_GREETER_ADDR=server:${SERVER_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - papersPleaseNetwork
networks:
  papersPleaseNetwork: {}
